paths:
    segmented_zarr_path: "/g/huber/projects/CODEX/BNHL"
    processed_zarr_path: "/g/huber/users/meyerben/data/codex/BNHL/zarrs_processed"
    abundance_path: "/g/huber/users/meyerben/data/codex/BNHL/ct_abundances"
    neighborhood_path: "/g/huber/users/meyerben/data/codex/BNHL/neighborhoods"
    nh_zarr_path: "/g/huber/users/meyerben/data/codex/BNHL/zarrs_with_neighborhoods"
    co_occurrences_path: "/g/huber/users/meyerben/data/codex/BNHL/co_occurrences"
    csv_path: "/g/huber/users/meyerben/data/codex/BNHL/csvs"
    adata_path: "/g/huber/users/meyerben/data/codex/BNHL/anndata"
    spatstat_csv_path: "/g/huber/users/meyerben/data/codex/BNHL/spatstat_csvs"
    valid_samples_path: "/g/huber/users/meyerben/notebooks/spatialproteomics_pipelines/bnhl_processing/data/valid_samples.txt"
    data_for_figure_path: "/g/huber/users/meyerben/data/codex/BNHL/figures/data"
    figure_path: "/g/huber/users/meyerben/data/codex/BNHL/figures"
    squidpy_csv_path:  "/g/huber/users/meyerben/data/codex/BNHL/squidpy_csvs"
    adata_with_nhs_path: "/g/huber/users/meyerben/data/codex/BNHL/anndata_with_nhs"
    squidpy_subset_csv_path:  "/g/huber/users/meyerben/data/codex/BNHL/squidpy_subset_csvs"